# Generated by Django 6.0.2 on 2026-02-22 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bidang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengirim', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('Keluhan', 'Keluhan'), ('Feedback', 'Feedback')], max_length=20)),
                ('isi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Tertunda', 'Tertunda'), ('Sedang Dikerjakan', 'Sedang Dikerjakan'), ('Selesai', 'Selesai')], default='Tertunda', max_length=30)),
                ('admin_bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keluhan.bidang')),
            ],
        ),
    ]
