# Generated by Django 6.0.2 on 2026-02-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidang',
            old_name='nama_bidang',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='laporan',
            old_name='nama_pengirim',
            new_name='chat_id',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='admin_bidang',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(default='Dikirim', max_length=50),
        ),
    ]
