# Generated by Django 6.0.2 on 2026-02-25 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0002_rename_nama_bidang_bidang_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
