# Generated by Django 6.0.2 on 2026-02-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0003_laporan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='show_in_recent',
            field=models.BooleanField(default=True),
        ),
    ]
