# Generated by Django 6.0.2 on 2026-02-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0004_laporan_hidden_at_laporan_show_in_recent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={'verbose_name_plural': 'Bidang'},
        ),
        migrations.AlterModelOptions(
            name='laporan',
            options={'ordering': ['-tanggal']},
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(choices=[('Dikirim', 'Dikirim'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Dikirim', max_length=50),
        ),
    ]
