# Generated by Django 6.0.2 on 2026-02-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0005_alter_bidang_options_alter_laporan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Bidang'},
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='created_at',
        ),
        migrations.AddField(
            model_name='laporan',
            name='nama_pengirim',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bidang',
            name='nama',
            field=models.CharField(choices=[('Sekretaris', 'Sekretaris'), ('Administrasi Umum dan Kepegawaian', 'Administrasi Umum dan Kepegawaian'), ('Administrasi Keuangan dan Pelaporan', 'Administrasi Keuangan dan Pelaporan'), ('Bidang Layanan E-Government', 'Bidang Layanan E-Government'), ('Bidang Pengelolaan Informasi Komunikasi Publik dan Statistik', 'Bidang Pengelolaan Informasi Komunikasi Publik dan Statistik')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan', to='keluhan.bidang'),
        ),
    ]
