# Generated by Django 6.0.2 on 2026-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0006_alter_bidang_options_remove_laporan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='selesai_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
