# Generated by Django 6.0.2 on 2026-03-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0007_laporan_selesai_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={'ordering': ['nama']},
        ),
    ]
