# Generated by Django 6.0.2 on 2026-03-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0008_alter_bidang_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Bidang'},
        ),
    ]
