# Generated by Django 6.0.2 on 2026-03-04 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0009_alter_bidang_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_pengampu', to='keluhan.bidang')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminbidang', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Bidang',
                'verbose_name_plural': 'Admin Bidang',
            },
        ),
    ]
