# Generated by Django 6.0.2 on 2026-03-04 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0010_adminbidang'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbidang',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminbidang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
