# Generated by Django 6.0.2 on 2026-03-04 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0011_adminbidang_aktif_adminbidang_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='dikirim_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_dikirim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporan',
            name='dikirim_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
